//======================================================================
//  Original credits
//======================================================================
//  DECORATE: 	Maelstrom
//	Sounds:		Id Software, Monolith Games
//  Sprites: 	Id Software (edits by Eriance, Maelstrom)
//	GLDEFs: 	Dreadopp, Sandypaper (Brightmaps)
//======================================================================
//  Additional credits
//======================================================================
//	ZScript:	Dutchygamer
//======================================================================

class PyroDemon : DMR_Cyberdemon
{
	Default
	{
		Tag "Archon";
		Health 5000;
		Scale 1.5;
		Obituary "%o was burnt to a crisp by an archon";
		HitObituary "%o was melted my an archon";
		Bloodcolor "75 25 00";
		SeeSound "pyro/see";
		PainSound "pyro/pain";
		DeathSound "pyro/death";
		ActiveSound "pyro/idle";
	}
	States
	{
	Spawn:
		PYRO AB 10 A_Look;
		Loop;
	See:
		PYRO A 3 A_Hoof;
		PYRO A 3 A_Chase;
		//TNT1 A 0 A_SpawnItemEx("WalkFire",0,0,0,1,0,0,0,128);
		PYRO BB 3 A_Chase;
		//TNT1 A 0 A_SpawnItemEx("WalkFire",0,0,0,1,0,0,0,128);
		PYRO CC 3 A_Chase;
		//TNT1 A 0 A_SpawnItemEx("WalkFire",0,0,0,1,0,0,0,128);
		PYRO D 3 A_Hoof;
		PYRO D 3 A_Chase;
		//TNT1 A 0 A_SpawnItemEx("WalkFire",0,0,0,1,0,0,0,128);
		Loop;
	Missile:
		TNT1 A 0 A_JumpIfCloser(350, "PyroBlast");
		TNT1 A 0 A_JumpIfCloser(500, "Comet");
		//TNT1 A 0 A_Jump(32,"Teleport");
		Goto FireShot;
	FireShot:
		PYRO EF 8 Bright A_FaceTarget;
		PYRO G 6 Bright {
			A_SpawnProjectile ("PyroDemonBall",56,0,0,0);
			A_SpawnProjectile ("PyroDemonBall",56,0,4,0);
		}
		PYRO H 4 Bright;
		PYRO IJ 6 Bright A_FaceTarget;	
		PYRO K 6 Bright {
			A_SpawnProjectile ("PyroDemonBall",56,0,0,0);
			A_SpawnProjectile ("PyroDemonBall",56,0,-4,0);
		}
		PYRO L 4 Bright;
		Goto See;
	PyroBlast:
		TNT1 A 0 A_Jump(128, "FireShot"); //chance to use the normal attack when in close range
		TNT1 A 0 A_Jump(32, "Comet"); //small chance to use the comet attack when in close range
		PYRO MN 8 Bright A_FaceTarget;
		PYRO O 8 Bright A_SpawnProjectile ("PyroDemonBlast",56,0,0,0);
		PYRO P 6 Bright;
		Goto See;
	Comet:
		TNT1 A 0 A_Jump(64, "FireShot"); //chance to use the normal attack when in close range
		TNTA A 0 A_PlaySound("pyro/see");
		PYRO MN 12 Bright A_FaceTarget;
		PYRO O 8 Bright {
			A_SpawnProjectile("PyroDemonCometSpawner",56,0,0,0);
			A_SpawnProjectile("PyroDemonCometSpawner",56,0,60,0);
			A_SpawnProjectile("PyroDemonCometSpawner",56,0,120,0);
			A_SpawnProjectile("PyroDemonCometSpawner",56,0,180,0);
			A_SpawnProjectile("PyroDemonCometSpawner",56,0,240,0);
			A_SpawnProjectile("PyroDemonCometSpawner",56,0,300,0);
		}
		PYRO P 6 Bright;
		Goto See;
	/*Teleport:
		PYRO O 1 A_FaceTarget;
		PYRO O 0 A_SpawnProjectile ("EscapeExplosion",56,10,0,0);
		PYRO O 0 A_Mushroom("PyroDemonMushroomBall", random(12,16), MSF_Classic, 4, 0.1);
		PYRO O 3;
		PYRO P 3 Bright;
		PYRO A 0 A_UnSetShootable;
		PYRO A 1 A_PlaySound("pyro/tele");
		PYRO A 1 A_SetTranslucent(0.90);
		PYRO A 1 A_SetTranslucent(0.80);
		PYRO A 1 A_SetTranslucent(0.70);
		PYRO A 1 A_SetTranslucent(0.60);
		PYRO A 1 A_SetTranslucent(0.50);
		PYRO A 1 A_SetTranslucent(0.40);
		PYRO A 1 A_SetTranslucent(0.30);
		PYRO A 1 A_SetTranslucent(0.20);
		PYRO A 1 A_SetTranslucent(0.10);
		TNT1 AAAAAAAAAA random(5,10) A_Wander;
		TNT1 AAAAAAAAAA random(5,10) A_Chase(null,null,CHF_FASTCHASE);
		PYRO A 1 A_PlaySound("pyro/tele");
		PYRO A 1 A_SetTranslucent(0.10);
		PYRO A 1 A_SetTranslucent(0.20);
		PYRO A 1 A_SetTranslucent(0.30);
		PYRO A 1 A_SetTranslucent(0.40);
		PYRO A 1 A_SetTranslucent(0.50);
		PYRO A 1 A_SetTranslucent(0.60);
		PYRO A 1 A_SetTranslucent(0.70);
		PYRO A 1 A_SetTranslucent(0.80);
		PYRO A 1 A_SetTranslucent(0.90);
		PYRO A 1 A_SetTranslucent(1.0);
		PYRO A 0 A_SpawnProjectile ("EscapeExplosion",56,10,0,0);
		PYRO O 0 A_Mushroom("PyroDemonMushroomBall", random(12,16), MSF_Classic, 4, 0.1);
		PYRO A 0 A_SetShootable;
		Goto See;*/
	Pain:
		PYRO Q 10 A_Pain;
		Goto See;
	Death:
		/*PYRO R 10 Bright;
		PYRO S 10 Bright A_Scream;
		PYRO T 10 Bright;
		PYRO U 10 Bright A_NoBlocking;
		PYRO VWX 6 Bright;
		PYRO Y 3 Bright;
		PYRO Z 30 Bright;
		PYRO Z -1 Bright A_BossDeath;
		Stop;*/
		PYRO R 10 Bright;
		PYRO S 10 Bright A_Scream;
		PYRO TUV 10;
		PYRO W 6;
		PYRO X 6 A_NoBlocking;
		PYRO Y 6;
		PYRO Z 50;
		PYRO Z -1 A_BossDeath;
		Stop;
	}
}

class PyroDemonBall : Actor
{
	Default
	{
		Radius 8;
		Height 8;
		Speed 20;
		DamageFunction(random(40,120));
		Projectile;
		RenderStyle "Add";
		DamageType "Fire";
		SeeSound "pyro/flame";
		DeathSound "pyro/flamepoof";
		Scale 1.2;
	}
	States
	{
	Spawn:
		FSHT AABB 2 BRIGHT {
			A_SpawnItemEx("DMR_LargeFireballTrail",-5,0,3,frandom(-1,0),frandom(-1,1),frandom(0,1));
			A_SpawnItemEx("PyroDemonBallTail",0,0,0,0,0,0);
		}
		Loop;
	Death:
		TNT1 AAAAAAAAAAAA 0 {
			A_SpawnItemEx("DMR_MediumFireDebris",random(-1,1),random(-1,1),random(-1,1),frandom(-2,2),frandom(-2,2),frandom(-1,2)); 
			A_SpawnItemEx("DMR_MediumFireBouncingDebris",random(-1,1),random(-1,1),random(-1,1),frandom(-2,2),frandom(-2,2),frandom(-1,2));
		}
		MISL B 8 Bright A_Explode(96);
		MISL C 6 Bright;
		MISL D 4 Bright;
		Stop;
	}
}

class PyroDemonBallTail : DMR_ProjectileTrail
{
	Default
	{
		Alpha 0.4;
	}
	States
	{
	Spawn:
		FRTB ABCDEFGHI 2 Bright;
		Stop;
	}
}

class PyroDemonBlast : DMR_GrenadeBase
{
	Default
	{
		DamageFunction(random(10,30));
		RenderStyle "Normal";
		SeeSound "pyro/blast";
		DeathSound "pyro/blastexplosion";
		Speed 12;
		Height 10;
		Radius 10;
		Scale 1.5;
		BounceSound "";
	}
	States
	{
	Spawn:
		TNT1 A 0 NoDelay {
			grenadeTimer = random(0,10);
		}
		COMT AABBCC 2 Bright {
			A_SpawnItemEx("DMR_LargeFireballTrail",-5,0,3,frandom(-1,0),frandom(-1,1),frandom(0,1));
			A_SpawnItemEx("PyroDemonBallTail",0,0,0,0,0,0);
			//detonate if timer runs out
			if(grenadeTimer >= 80) {
				return ResolveState("XDeath");
			}
			grenadeTimer += 1;
			return ResolveState(null);
		}
		Goto Spawn+1;
	//stopped moving
	Death:
	//timer ran out
	XDeath:
		TNT1 AAAAAAAAAAAA 0 {
			A_SpawnItemEx("DMR_MediumFireDebris",random(-1,1),random(-1,1),random(1,3),frandom(-2,2),frandom(-2,2),frandom(-1,2)); 
			A_SpawnItemEx("DMR_MediumFireBouncingDebris",random(-1,1),random(-1,1),random(1,3),frandom(-2,2),frandom(-2,2),frandom(-1,2));
		}
		COMT D 3 Bright {
			A_Mushroom("PyroDemonMushroomBall",random(6,8),MSF_Classic|MSF_DontHurt,4,0.1);
			A_Explode(40,80);
		}
		COMT EFGHI 3 Bright;
		Stop;
	}
}

class PyroDemonMushroomBall : Actor
{
	Default
	{
		Radius 8;
		Height 8;
		DamageFunction(random(4,12));
		Speed 15;
		SeeSound "pyro/bomb";
		DeathSound "pyro/bombhit";
		Projectile;
		RenderStyle "Add";
		Alpha 0.7;
		-NoGravity;
		Gravity 0.125;
		BounceType "Doom";
		DamageType "Fire";
	}
	States
	{
	Spawn:
		RBAL AAAABBBB 1 Bright;
		Goto Spawn +2;
	Death:
		RBAL DEFGHI 4 Bright;
		Stop;
	}
}

class PyroDemonCometSpawner : Actor
{
	Default
	{
		Radius 0;
		Height 0;
		Speed 8;
		Projectile;
		BounceType "Doom";
		+Ripper;
		+CeilingHugger;
		+DontHarmSpecies;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_Jump(5,"Death"); //small chance to kill itself
		TNT1 AAAAAA 1 A_Wander;
		TNT1 A 8 A_SpawnProjectile("PyroDemonFallingComet",-24,random(0,128),random(0,360),2,random(1,89));
		Loop;
	Death:
		Stop;
	}
}

class PyroDemonFallingComet : AfritComet
{
	Default
	{
		Speed 0;
		//Damage 8;
		-NoGravity;
		-Float;
		+SpawnCeiling;
	}
	States
	{
	Spawn:
		COMT AABBCC 2 Bright { 
			A_SpawnItemEx("AfritCometTrail",0,0,0);
			A_SpawnItemEx("DMR_MediumFireballTrail",0,0,2,frandom(-1,0),frandom(-1,1),frandom(0,1)); 
		}
		Loop;
	Death:
		TNT1 A 0 {
			A_SetScale(1);
		}
		TNT1 AAAAAA 0 {
			A_SpawnItemEx("DMR_MediumFireDebris",random(-1,1),random(-1,1),random(-1,1),frandom(-2,2),frandom(-2,2),frandom(-1,2)); 
			A_SpawnItemEx("DMR_MediumFireBouncingDebris",random(-1,1),random(-1,1),random(-1,1),frandom(-2,2),frandom(-2,2),frandom(-1,2));
		}
		COMT D 3 Bright A_Explode(20,80);
		COMT EFGHI 3 Bright;
		Stop;
	}
}

//unused

class PyroDemonBlastExplosion : Actor
{
	Default
	{
		Radius 11;
		Height 8;
		Speed 18;
		Damage 10;
		Projectile;
		-NoGravity;
		Obituary "%o was killed by a firebomb explosion.";
	}
	States
	{
	Spawn:
		FRME A 1 Bright;
		Loop;
	Death:
		FRME A 0;
		FRME A 0 A_PlaySound("pyro/blastexplosion");
		FRME A 3 Bright A_Explode(32, 128);
		FRME B 1 Bright A_Mushroom("PyroDemonMushroomBall", random(6,8), MSF_Classic, 4, 0.1);
		FRME B 2 Bright;
		FRME CDEFGHIJKLMNOPQRS 3 Bright;
		Stop;
	}
}

class EscapeExplosion: Actor
{
	Default
	{
		SeeSound "pyro/explosion";
		Radius 8;
		Height 56;
		Speed 0;
	}
	States
	{
	Spawn:
		NKXP B 3 Bright;
		NKXP C 3 Bright;
		NKXP D 3 Bright A_Explode(50, 192);
		NKXP EFGHIJKLMNOPQRSTUV 3 Bright;
		Stop;
	}
}

class WalkFire : Actor
{
	Default
	{
		+NoClip;
		+Missile;
		+DropOff;
		+Randomize;
		Scale 1.5;
		Speed 1;
		RenderStyle "Add";
		Alpha 0.67;
	}
	States
	{
	Spawn:
		TNT1 A 8;
		FRTF A 3 Bright;
		FRTF A 0 ;
		FRTF B 3 Bright;
		FRTF B 0 ;
		FRTF C 3 Bright;
		FRTF C 0 ;
		FRTF C 0 ;
		FRTF C 0 A_Jump(191,4);
		FRTF C 0 A_SpawnProjectile("WalkFire", 0, 24, 0);
		FRTF C 0 A_SpawnProjectile("WalkFire", 0, 0, 0);
		FRTF C 0 A_SpawnProjectile("WalkFire", 0, -24, 0);
		FRTF DEFGHIJKLMNO 3 Bright;
		Stop;
	}
}

class AfritCometDeath : Actor
{
	Default
	{
		PROJECTILE;
		RENDERSTYLE "ADD";
		+NOCLIP;
		ALPHA 0.7;
	}
	States
	{
	Spawn:
		COMT FGHI 3 Bright;
		Stop;
	}
}
class PyroDemonCometDeathGlow : AfritCometDeathGlow
{
	Default
	{
		Scale 3.0;
	}
	States
	{
	Spawn:
		FRTB ABCDEFGHI 3 Bright;
		Stop;
	}
}
class PyroDemonCometDeath : AfritCometDeath
{
	Default
	{
		Scale 1.5;
	}
	States
	{
	Spawn:
		COMT FGHI 3 Bright;
		Stop;
	}
}