//======================================================================
//  Original credits
//======================================================================
//  DECORATE: 	???
//	Sounds:		???
//  Sprites: 	??? (edits by ???)
//	GLDEFs: 	n/a
//======================================================================
//  Additional credits
//======================================================================
//	ZScript:	Dutchygamer
//======================================================================

class InfernoElemental : DMR_PainElemental
{  
	Default
	{
		Tag "Inferno Elemental";	
		Health 450;
		Obituary "%o got blasted by an Inferno Elemental.";
		DamageFactor "Fire", 0.5;
		+BRIGHT;
		SeeSound "infernal/see";
		PainSound "infernal/pain"; 
		DeathSound "infernal/death";
		bloodcolor "orange";
	}
	States 
	{ 
	Spawn: 
		INFR A 10 A_Look;
		Loop;
	See: 
		INFR AABBCCDD 3 A_Chase;
		Loop;
	Missile:
		TNT1 A 0 A_Jump(128,"ExplosiveBall");
		goto LostSoul;
	LostSoul:
		INFR HI 5 A_FaceTarget;
		INFR J 4 A_FaceTarget;
		INFR J 1 A_PainAttack("DMR_LostSoul"); //TODO normal lost soul for now
		goto See;
	ExplosiveBall:
		INFR HI 5 A_FaceTarget;
		INFR J 5 A_SpawnProjectile("InfernalExplosiveBall",24);
		goto See;
	Pain: 
		INFR K 6;
		INFR K 6 A_Pain;
		Goto See;
	Death:
		INFR L 6;
		INFR M 6 A_Scream;
		INFR N 6;
		INFR O 6;
		INFR P 6 A_PainDie("DMR_LostSoul");
		INFR Q 6;
		Stop;
	} 
}