//======================================================================
//  Original credits
//======================================================================
//  DECORATE: 	Eric Ou
//	Sounds:		Id Software
//  Sprites: 	Id Software (edits by Eric Ou)
//	GLDEFs: 	n/a
//======================================================================
//  Additional credits
//======================================================================
//	ZScript:	Dutchygamer
//======================================================================

class Mygalotron : DMR_Arachnotron
{
	Default
	{		
		Tag "Widotron";
		Obituary "%o got wasted by a Widotron.";
		Health 850;
		Speed 16;
		Scale 1.1;
		PainChance 50;
	}
	states
	{
	Spawn:
		ARAC AB 10 A_Look;
		Loop;
	See:
		ARAC A 20;
		ARAC A 3 A_BabyMetal;
		ARAC ABBCC 3 A_Chase;
		ARAC D 3 A_BabyMetal;
		ARAC DEEFF 3 A_Chase;
		Goto See+1;
	Missile:
		ARAC A 20 bright A_FaceTarget;
		ARAC G 2 bright Light("DMR_ArachnotronFire") A_SpawnProjectile("DMR_AracknightPlasma",22);
		ARAC H 2 bright;
		ARAC H 1 bright A_SpidRefire;
		goto Missile+1;
	Pain:
		ARAC I 3;
		ARAC I 3 A_Pain;
		Goto See+1;
	Death:
		ARAC J 20 A_Scream;
		ARAC K 7 {
			A_NoBlocking();
			A_SpawnItemEx("DMR_MonsterDeathExplosion",random(10,-10),0,random(20,30));
		}
		ARAC LMNO 7;
		ARAC P -1 A_BossDeath;
		Stop;
	Raise:
		ARAC P 5;
		ARAC ONMLKJ 5;
		Goto See+1;
	}
}

class DMR_AracknightPlasma : DMR_ArachnotronPlasma
{
	Default
	{
		Speed 35;
		DamageFunction(random(10,30));
		RenderStyle "Add";
		Alpha 0.75;
		SeeSound "baby/attack";
		DeathSound "baby/shotx";
		Decal "ArachnotronScorch";
	}
	states
	{
	Spawn:
		FS03 AAABBB 2 Bright  {
			//A_SpawnItemEx("DMR_ArachnotronPlasmaTrail",frandom(-0.5,0.5),frandom(-0.5,0.5),frandom(-0.5,0.5));
		}
		Loop;
	Death:
		//TNT1 A 0 {
		//	A_SpawnItemEx("DMR_PlasmaImpactFlare");
		//}
		FS03 HIJG 5 Bright;
		Stop;
	}
}



//TODO unused
class MygalotronBall : DMR_HellRune
{  
	Default
	{
		DamageFunction(random(8,24));
		Speed 20;
		Scale 0.8;
	}
}

class MygalotronExplosiveBall : DMR_HellRuneExplosive
{  
	Default
	{
		Speed 16;
		DamageFunction(random(20,60));
	}
}