Class ChaingunGuyReplacer: RandomSpawner replaces Chaingunguy
{
	Default
	{
		DropItem "DMR_ChaingunGuy", 255, 100;
		DropItem "FormerGunnerCommando", 255, 20;
		DropItem "FormerRocketeer", 255, 20;
		DropItem "FormerPyroTechnician", 255, 10;
		DropItem "FormerViralAgent", 255, 10;
		DropItem "FormerPlasmaCommando", 255, 10;
		DropItem "FormerBFGCommando", 255, 4;
		DropItem "FormerCyborgCommando", 255, 2;
	}
}