Class ChaingunGuyReplacer: RandomSpawner replaces Chaingunguy
{
	Default
	{
		DropItem "DMR_ChaingunGuy", 255, 100;
		DropItem "FormerGunnerCommando", 255, 20;
		DropItem "FormerRocketeer", 255, 20;
		DropItem "FormerChemWarrior", 255, 10;
		DropItem "FormerViralAgent", 255, 10;
		DropItem "FormerPlasmaCommando", 255, 10;
		DropItem "FormerSpecOpsElite", 255, 10;
		DropItem "CyborgReaper", 255, 5;
		DropItem "FormerBFGCommando", 255, 4;
		DropItem "CyborgCommando", 255, 1;
	}
}