Class ShotgunGuyReplacer: RandomSpawner replaces Shotgunguy
{
	Default
	{
		DropItem "DMR_ShotgunGuy", 255, 100;
		DropItem "FormerStaffSargeant", 255, 20;
		DropItem "FormerAssaultSargeant", 255, 20;
		DropItem "FormerQuartermaster", 255, 8;
		DropItem "FormerCyborg", 255, 4;
	}
}

// suicide guy itself is a collection of suicide guy variants
Class SuicideGuy : RandomSpawner
{
	Default
	{
		DropItem "SuicideGuyExplosive";
		DropItem "SuicideGuyGas";
	}
}
