Class DMR_ShotgunGuy: ShotgunGuy 
{
	Default
	{
		Tag "Shotgun zombie";
		Gibhealth -20; //all lower tier monsters (zombies -> imp) have 20 gibhealth
	}
	States
	{	
	Missile:
		SPOS E 10 A_FaceTarget;
		SPOS F 10 BRIGHT Light("DMR_RifleFire") {
			A_PlaySound("shotguy/attack", CHAN_WEAPON);
			A_CustomBulletAttack(22.5,0,3,random(6,12),"BulletPuff",0,CBAF_NORANDOM);
		}
		SPOS E 10;
		Goto See;
	}
}